version: '3'
services: 
  slack-services:
    image: "slack-image:1.00"
    container_name: "slack-container"
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/usr/req